"""Serve one bounded Base64 URI-line subscription body over plain HTTP.

The body is generated by the workflow and mounted read-only, so this service
holds no credential logic of its own.  It exists so the lane exercises the real
``V2RAY_SUBSCRIPTION`` fetch path against a service name rather than a provider.
"""

import os
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

FEED_PATH = "/subscription"


class _Handler(BaseHTTPRequestHandler):
    server_version = "jerryproxy-e2e-subscription"
    sys_version = ""

    def do_GET(self):  # noqa: N802 - BaseHTTPRequestHandler's required name
        if self.path != FEED_PATH:
            self.send_response(404)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        try:
            with open(self.server.feed, "rb") as stream:
                payload = stream.read()
        except OSError:
            # A missing mount is a setup defect; report it as a server error
            # rather than serving an empty body a test might accept.
            self.send_response(500)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, format, *args):  # noqa: A002 - signature is fixed upstream
        # Never log the body: it carries the generated node URIs.
        sys.stderr.write("subscription %s\n" % (format % args))


def main():  # type: () -> int
    feed = os.environ.get("JERRYPROXY_E2E_FEED", "/feed/subscription")
    if not os.path.isfile(feed):
        sys.stderr.write("subscription feed is missing: %s\n" % feed)
        return 2
    port = int(os.environ.get("JERRYPROXY_E2E_SUBSCRIPTION_PORT", "8081"))
    server = ThreadingHTTPServer(("0.0.0.0", port), _Handler)
    server.feed = feed
    sys.stderr.write("subscription listening on 0.0.0.0:%d\n" % port)
    server.serve_forever()
    return 0


if __name__ == "__main__":
    sys.exit(main())
